groups:
- name: instance_down
  rules:
  # Alert for any instance that is unreachable for > 30s.
  - alert: InstanceDown
    expr: up{instance='collectd_exporter:9103'} == 0
    for: 30s
    labels:
      severity: critical
      owner: opaliwal
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."