global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'collectd_exporter'
    static_configs:
      - targets: ['collectd_exporter:9103']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - "alert_rules.yml"